Changes to story-postcard.hbs, date placement with clock icon
AdvisorySG/ghost-advisory-theme pull request #280
Opened 2021-08-05 09:16 UTC by Eykf1997

Changing of date placement

2021-08-08 14:23 UTC, wei2912 requested changes
Code looks good, although I think there's a leftover " - " in the post title and excessive space from excerpt to date. Also, the date's a bit too close to the corner of the card.

![image](https://user-images.githubusercontent.com/2070423/128635318-251a715b-2eef-4f4d-b935-2ec11bcfd617.png)

2021-08-10 06:18 UTC, Eykf1997 commented
Updated date placement.

2021-08-13 07:50 UTC, wei2912 requested changes
Few minor changes to be made, otherwise LGTM.

2021-08-13 07:50 UTC, wei2912 commented on partials/story-postcard.hbs
>                      {{primary_tag.name}} -
Do delete the leftover " - " here.

2021-08-13 07:50 UTC, wei2912 commented on partials/story-postcard.hbs
>                      No tag -
See L12.

2021-08-13 07:50 UTC, wei2912 commented on partials/story-postcard.hbs
> +
Please delete this blank line.

2021-08-13 07:50 UTC, wei2912 commented on partials/story-postcard.hbs
> +            <div class="text-sm absolute right-4 bottom-4" >
Delete the extra space before the `>`

2021-08-14 04:26 UTC, wei2912 commented
Squashed and merged in https://github.com/AdvisorySG/ghost-advisory-theme/commit/65314182c5ad6926d7dba7f00b19ac8900bcb613, thanks!

2021-08-14 04:26 UTC, closed without merging